<?php
/**
 * Created by PhpStorm.
 * User: marius
 * Date: 18.11.22
 * Time: 16.30
 */

namespace PlumTreeSystems\SyliusSecureTradingPlugin\Form\Type;

class SecureTradingGatewayConfigurationType extends \Symfony\Component\Form\AbstractType
{
    public function buildForm(\Symfony\Component\Form\FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }
}